### ISSUE TITLE
Should defcon be listed in requirements.txt?

### ISSUE THREAD

**Issue by jbicha** [googlei18n/cu2qu#148]
defcon is used in Lib/cu2qu/cli.py 

Should it be listed in requirements.txt?

**Comment by anthrotype** [comment]
good point. Technically one can pass cu2qu a compatible Font object that “quacks” like a defcon duck. But in the cu2qu script (which was added recently) we do import defcon so if you run the script, it is required.
Let me think about it.

**Comment by anthrotype** [comment]
it appears that my previous self already solved this problem
https://github.com/googlei18n/cu2qu/blob/dc44ddecbc1253ad857edd19e66b53d53437cbc5/setup.py#L186

defcon is _already_ listed in `extras_require`, thus if one does `pip install cu2qu[cli]` that will also pull in defcon as a dependency _and_ install the `cu2qu` console script entry point. Otherwise they won't, not automatically.

I think this is acceptable and good as is. I don't want to make defcon a required, runtime dependency of cu2qu. It's only required to run the console script or the test suite.

By the way, since I know you are packaging up these font development tools (is it Debian?), please note that the _canonical_ source of install-time dependencies for any python libraries is not the `requirements.txt` file, but the `install_requires` keyword in the `setup.py`, plus any `extras_require` if present, for optional dependencies.
The way I use `requirements.txt` here is to create a reproducible tox environment for self-testing purposes, with pinned-down versions (`==`) of each install requirements.

You see, defcon is already listed in `test-requirements.txt`. It doesn't change anything if I move it to the other. Both `requirements.txt` and `test-requirements.txt` are installed by tox in the test environment, one after the other. Ok, I'll move it to `requirements.txt`, but it doesn't change the fact that it is not required to install cu2qu unless you want to use the console script.

**Comment by jbicha** [comment]
Yeah, we need these in Debian because some fonts are built with fontmake. fontmake has a large list of dependencies!

**Comment by anthrotype** [comment]
I know! :smile:

**Comment by anthrotype** [comment]
btw, thanks for doing this!
