### ISSUE TITLE
fonts/dict are unsorted

### ISSUE THREAD

**Issue by typemytype** [googlei18n/cu2qu#48]
This raises an AssertionError:
https://github.com/googlei18n/cu2qu/blob/master/Lib/cu2qu/ufo.py#L230

even when two or more ufo defcon objects with the same charset are provided.

The order is setup in the `_zip` function https://github.com/googlei18n/cu2qu/blob/master/Lib/cu2qu/ufo.py#L40-L48
but the order is rather arbitrary cause fonts and glyphSets are dicts.

**Comment by anthrotype** [comment]
Good point...

It's strange we didn't catch this before. It's probably because the sets of keys is hashed in the same way when UFOs with same contents.plist are first loaded from disk (e.g. when running fontmake), but then this might change if in the process some glyphs are removed or inserted from the defcon fonts.

We should definitely not assume that __iter__ (as used by zip) always returns glyphs in the same order for all the fonts, but instead we groups glyphs with the same name across all fonts and convert those compatibly (and possibly convert the remaining ones one by one).

**Comment by typemytype** [comment]
yes, Im adding glyphs in the fly... 
and whenever a dict object is altered the order can change


gr Frederik
www.typemytype.com

**Comment by anthrotype** [comment]
Thanks for spotting this!

**Comment by typemytype** [comment]
a simple test case: 

```python
from cu2qu.ufo import fonts_to_quadratic
from defcon import Font

from random import shuffle

def drawSomeThing(g):
    pen = g.getPen()
    
    pen.moveTo((100, 100))
    pen.lineTo((100, 200))
    pen.lineTo((200, 200))
    pen.curveTo((220, 166), (220, 133), (200, 100))
    pen.closePath()

glyphNames = list("abcdeABC")

ufos = []

for i in range(10):
    
    f = Font()
    f.info.unitsPerEm = 1000 # this seems to be required?? (I will put this in an other issue)
    
    shuffle(glyphNames)
    for glyphName in glyphNames:
        
        f.newGlyph(glyphName)
    
        drawSomeThing(f[glyphName])
    ufos.append(f)


for font in ufos:
    print font.keys()
    
fonts_to_quadratic(ufos)
```

**Comment by behdad** [comment]
> (and possibly convert the remaining ones one by one).

Remaining ones also should be converted all compatibly across masters that have them.

**Comment by anthrotype** [comment]
of course, that's what I meant ;)

**Comment by anthrotype** [comment]
@behdad I addressed this issue in https://github.com/googlei18n/cu2qu/pull/50
